### ISSUE TITLE
Improper input filepath inference in SmartPeakCLI

### ISSUE THREAD

**Issue by buijt** [dmccloskey/SmartPeak2#396]
**Describe the bug**
Providing a sequence.csv file will cause the SmartPeak CLI to improperly infer the location of parameters.csv and traml.csv as inside a subdirectory named "sequence.csv" instead of searching the parent directory of the sequence.csv file.

**To Reproduce**
Provide SmartPeak CLI with a sequence file, e.g. with the command `SmartPeakCLI.exe -l .\sequence.csv`. (Providing relative / absolute paths will both cause this bug to manifest)

**Expected behavior**
Expected SmartPeak to find `parameters.csv` and `traml.csv` in the parent directory as `sequence.csv`, instead of treating `sequence.csv` as the directory to search in.

**logs**
 - Windows: 
[smartpeak_log_2021-07-19.zip](https://github.com/AutoFlowResearch/SmartPeak/files/6844346/smartpeak_log_2021-07-19.zip)

**data**
N/A

**Version information**
 - OS: Windows 10 v1909
 - Version 1.11.0

**Additional context**
Would you consider adding separate options for specifying a path to the MZML directory and parameters.csv file, instead of implicitly assuming everything to be deposited in the same directory?

**Comment by bertrandboudaud** [comment]
Seems to be an improper way of handling separator. if we use / instead of \ it will work.
we will fix it.
