### ISSUE TITLE
Mild confusion between input traML column names and output PivotTable column names

### ISSUE THREAD

**Issue by buijt** [dmccloskey/SmartPeak2#409]
**Describe the bug**
The first two columns in the PivotTable are "component_group_name" and "component_name." I would expect the following correspondence between the PivotTable columns and the TraML columns:

| PivotTable column | expected to correspond to | TraML column |
| --- | --- | --- |
| component_group_name | | transition_group_id |
| component_name | | transition_name

However, the contents of the PivotTable columns are in fact reversed from my expectation, and the column correspondence is this:

| PivotTable column | actually corresponds to | TraML column |
| --- | --- | --- |
| component_group_name | | transition_name |
| component_name | | transition_group_name

I would consider this a bug since the columns are not as expected. Or perhaps I am misunderstanding the meaning of the output column names.

**To Reproduce**
1. Run SmartPeak and export a PivotTable
2. View columns from TraML and compare to PivotTable

**Expected behavior**
| PivotTable column | expected to correspond to | TraML column |
| --- | --- | --- |
| component_group_name | | transition_group_id |
| component_name | | transition_name

**Screenshots**
The following is the TraML for the example dataset LCMS_MRM_Unknowns:

![image](https://user-images.githubusercontent.com/44679745/129818291-c7198b05-8cd0-4326-aac7-3bc289f32d3d.png)

And the following is the PivotTable exported from running the LCMS MRM workflow preset:

![image](https://user-images.githubusercontent.com/44679745/129818381-400937f2-af33-44b8-b3f1-caa670b5d605.png)

**data**
None to share

**Version information**
 - OS: Windows 10
 - Version 1.12.0

**Comment by dmccloskey** [comment]
That is a bug.  Thank you for identifying that.
