### ISSUE TITLE
Rendering issue with Calibrators screen, calibration curves

### ISSUE THREAD

**Issue by buijt** [dmccloskey/SmartPeak2#411]
**Describe the bug**
I am looking at the calibration curve figures generated from the example dataset for LCMS MRM Standards, and the GUI is connecting the dots in a bizarre manner. The line fit drawing appears to be connecting the last calibration point back to the coordinates (0, 0) in the figure, then drawing another line from (0, 0) to (inf, inf) (or at least some large value outside of the render window).

**To Reproduce**
1. Load the [LCMS MRM Standards example dataset](https://github.com/AutoFlowResearch/SmartPeak/tree/develop/src/examples/data/LCMS_MRM_Standards) into SmartPeak 1.12.0
2. Run workflow
3. Open Calibrators screen and select some transitions to plot
4. The calibration curve figures look odd

**Expected behavior**

**logs**
Attach all recent SmartPeak log files which can be found in the following locations :
 - Windows: 
[smartpeak_log_2021-08-23_10-31-38.log](https://github.com/AutoFlowResearch/SmartPeak/files/7034454/smartpeak_log_2021-08-23_10-31-38.log)

[smartpeak_log_2021-08-23_12-04-42.log](https://github.com/AutoFlowResearch/SmartPeak/files/7034455/smartpeak_log_2021-08-23_12-04-42.log)

**Video**

https://user-images.githubusercontent.com/44679745/130508274-2ff40112-3658-46a5-8dd9-ca6b3fe95b8e.mp4

**Version information**
 - OS: Windows 10
 - SmartPeak ver. 1.12.0

**Additional context**

**Comment by bertrandboudaud** [comment]
It seems the concentration data need to be sorted before being displayed. The x values go from 0 to 8 but are not sorted
![image](https://user-images.githubusercontent.com/1705849/131352515-ac1b9cae-a493-40a2-8db9-1128aa518f3d.png)
