### ISSUE TITLE
QC_transition_message and QC_transition_group_message do not appear in the PivotTable

### ISSUE THREAD

**Issue by buijt** [dmccloskey/SmartPeak2#414]
**Describe the bug**
Hello. The Report function has an ability to export a meta_value called "QC_transition_message" and "QC_transition_group_message." I understand this message to contain information regarding which QC threshold had failed the QC rules defined in featureQCComponents.csv and featureQCComponentGroups.csv. However, I notice that recently this is not included PivotTable report, but they are included in the FeatureDB report!

I believe this to be a bug where the PivotTable does not include all the Metadata as specified.

**To Reproduce**
1. Run a dataset that contains a featureQCComponents.csv and featureQCComponentGroups.csv, e.g. the LCMS_MRM_Unknowns example dataset on GitHub.
2. At the top of the GUI, open Actions > Report.
3. Check off all Sample Types, then in the Metadata column, check off "QC_transition_message" and "QC_transition_group_message."
4. Press "Create PivotTable.csv" and "Create FeatureDB.csv"
5. Inspect PivotTable.csv and there is no data reported for these meta_values.
6. Inspect FeatureDB.csv and scroll all the way to the right. There are data columns for "QC_transition_message" and "QC_transition_group_message."

**Expected behavior**
PivotTable contains data for "QC_transition_message" and "QC_transition_group_message."

**Version information**
 - OS: Windows 10
 - Version 1.12.0

**Comment by bertrandboudaud** [comment]
Hello,

it seems we filter out all metadata with value 0.0 (datum.f_ != 0.0).
@dmccloskey do you know the reason of this?

```
            if (datum.getTag() == CastValue::Type::FLOAT && datum.f_ != 0.0 && !std::isnan(datum.f_)) { // Skip NAN (replaced by 0 later)
              data_dict[sample_name].emplace(row_tuple_name, datum.f_);
              columns.insert(sample_name);
              rows.insert(row_tuple_name);
            }
```

**Comment by dmccloskey** [comment]
That looks like a bug.  We want to replace NaN with a 0 but instead it just drops the row how it is written currently.
