### ISSUE TITLE
SmartPeak crashes when given invalid directory

### ISSUE THREAD

**Issue by buijt** [dmccloskey/SmartPeak2#415]
**Describe the bug**
Self-explanatory title

**To Reproduce**
1. Open SmartPeak GUI
2. File > Open session from sequence...
3. Press "Change dir" button and provide a nonsense path name, e.g. "abc" then press "Set"
4. SmartPeak crashes

**Expected behavior**
SmartPeak gracefully surfaces an error about invalid path.

**logs**
[smartpeak_log_2021-08-30_11-06-10.log](https://github.com/AutoFlowResearch/SmartPeak/files/7078606/smartpeak_log_2021-08-30_11-06-10.log)

**Version information**
 - OS: Windows 10
 - Version 1.12.0

**Comment by ahmedskhalil** [comment]
Thanks, will be fixed in the upcoming release.

**Comment by ghost** [comment]
This will be fixed in the upcoming version 1.13.0 which will be released soon.
