### ISSUE TITLE
SmartPeakCLI not included in the Docker image

### ISSUE THREAD

**Issue by buijt** [dmccloskey/SmartPeak2#416]
Hello. I contacted the team that manages my institution's computing cluster to ask them to install SmartPeak onto our Linux server and one of the team members mentioned offhand to me that they initially attempted to build a Docker image for SmartPeak using the provided Dockerfile, but that SmartPeakCLI was unfortunately not included.

I recall a while back that the SmartPeak team needed to update the build instructions to compile SmartPeakCLI when compiling normally from source; is it possible that there was an oversight in updating the Docker build instructions?

Let me know if you need more details to look into this. I am not directly involved in the installation process for my institution's computing cluster but I can request more information if necessary.

Many thanks.

**Comment by bertrandboudaud** [comment]
Dear Jonathan,

When building new releases, we provide installation packages: windows .exe, mac os, and deb packages for Linux. 
What has been done previously was to include the SmartPeakCLI in the deb package and windows, which was missing.

The dockerfile has not been updated for a while.
we can plan to do it.

with regards,
bertrand

**Comment by ghost** [comment]
Please follow the Readme in : [autoflowresearch/smartpeak-cli](https://hub.docker.com/r/autoflowresearch/smartpeak-cli) .
