### ISSUE TITLE
SmartPeakGUI - Saving PivotTable report produces generates a CSV that looks like FeatureDB

### ISSUE THREAD

**Issue by buijt** [dmccloskey/SmartPeak2#441]
**Describe the bug**
When creating a PivotTable report through the Windows GUI, the generated CSV file looks like the FeatureDB report, and not like a PivotTable report. When running SmartPeak through the CLI, the PivotTable report looks the same as in previous versions.

**To Reproduce**
1. Open SmartPeak GUI
2. Load any dataset and run workflow
3. Actions > Report > Create Pivot Table
4. Open PivotTable.csv and see data

**Expected behavior**
PivotTable.csv should have the format same as before, with columns: component_name, component_group_name, meta_value, sample1, sample2, ...

**log**
 - Windows: [smartpeak_log_2021-10-15_16-30-48.log](https://github.com/AutoFlowResearch/SmartPeak/files/7356388/smartpeak_log_2021-10-15_16-30-48.log)

**data**
From the LCMS_MRM_Unknowns example dataset:
- [old_PivotTable.csv](https://github.com/AutoFlowResearch/SmartPeak/files/7356390/old_PivotTable.csv)
- Generated from v1.15.0 GUI [PivotTable.csv](https://github.com/AutoFlowResearch/SmartPeak/files/7356391/PivotTable.csv)

**Version information**
 - OS: Windows 10
 - Version 1.15.0

**Comment by bertrandboudaud** [comment]
Hello,

Sorry for that, this is indeed a regression from 1.15.0
