### ISSUE TITLE
No information contained in PivotTable meta_values: QC_transition_group_message, QC_transition_message

### ISSUE THREAD

**Issue by buijt** [dmccloskey/SmartPeak2#442]
**Describe the bug**
Following up from #414, although the meta_value rows for QC_transition_group_message and QC_transition_message are no longer dropped from the PivotTable.csv export, the rows themselves contain only 0s.

**To Reproduce**
1. Load any dataset into SmartPeak
2. Run workflow and export PivotTable report
3. View PivotTable.csv

**Expected behavior**
QC_transition_group_message, QC_transition_message should contain a text message mentioning the QC rules that failed, much like the text message included in the columns in FeatureDB report

**data**
This is from the LCMS_MRM_Unknowns example data. The very first entry fails the QC rules but the "_message" row contains no helpful information. 
- [PivotTable.csv](https://github.com/AutoFlowResearch/SmartPeak/files/7356418/PivotTable.csv)

**Version information**
 - OS: Windows 10
 - Version 1.15.0

**Comment by dmccloskey** [comment]
I believe this should have been taken care of in one of our last releases.  Please get back to us if the problem still persists.
