### ISSUE TITLE
FeatureDB - QC_transition_group_pass, QC_transition_pass are empty when component fails

### ISSUE THREAD

**Issue by buijt** [dmccloskey/SmartPeak2#443]
**Describe the bug**
QC_transition_group_pass and QC_transition_pass columns in FeatureDB.csv either have a value of 1 or none. In the PivotTable report, these values are either 0 or 1. I believe the FeatureDB "pass" columns should be consistent and fill these entries with 0 as well, instead of leaving the entry blank.

**Expected behavior**
Passed components contain a value of 1, and failed components contain a value of 0.

**data**
You can view the QC_transition_group_pass and QC_transition_pass columns from the FeatureDB report from the LCMS_MRM_Unknowns example dataset: [FeatureDB.csv](https://github.com/AutoFlowResearch/SmartPeak/files/7356424/FeatureDB.csv)
 
**Version information**
 - OS: Windows 10
 - Version: 1.15.0

**Comment by dmccloskey** [comment]
I believe this should have been taken care of in one of our last releases.  Please get back to us if the problem still persists.
