### ISSUE TITLE
Improving Calibrators plot

### ISSUE THREAD

**Issue by bertrandboudaud** [dmccloskey/SmartPeak2#498]
**Describe the bug**
The calibrator Plot needs some improvments.

**To Reproduce**
1. Open the HPLC_UV_Standards example
2. Click on Action > run workflow
3. Click on "View" > Calibrators
4. Select 5-HTP in the transitions explorer

![image](https://user-images.githubusercontent.com/1705849/149884928-738baa4a-9ae4-4fea-adb2-8fbc7f8af40e.png)

**Expected behavior**
- Not all the points (5HTP-pts, the blue points in the screenshot) are displayed. only the ones that have not been excluded by the calibration curve algorithm are displayed. we would like to have all the points displayed. excluded points and non excluded points may be displayed with a different shape.
- Having the point behind the line is not convenient. On another side, having them on the top can lead to confusion. maybe they can be the same color, but with a different shape.
- Add the possibility to hide the points, and/or the curve.
- Add some margin on top and right
- Add a zoomer item as other plots do
- Add some details about the curve: the parameters used and the one deducted: transformation_model, transformation_model_param_y_weight, ...

**Version information**
1.18.

**Comment by dmccloskey** [comment]
A few other points to potentially add to the **Expected Behavior**
- Show raw points even if there is no quantitation method or line of best fit
- Filled points could be used for "fitted" points and unfilled points could be used for "unfitted" points
