### ISSUE TITLE
Use ImPlot zooming feature

### ISSUE THREAD

**Issue by bertrandboudaud** [dmccloskey/SmartPeak2#506]
We want to use the facilities provided by ImPlot to navigate into the chromatograms and the spectrograms.

**Comment by dmccloskey** [comment]
The only complications I can think of would be keeping the sliders that determine the ranges of x axis values in sync. Perhaps even allowing the user to reset to the original view with some sort of "reset" layout button would also be a good combo?

**Comment by bertrandboudaud** [comment]
Yes, actually we can remove the sliders at all. with the Calibration curve improvement that is WIP, we can see that using the mouse wheel to zoom out/in, and have the box selection is very convenient.
And as for the Calibration curve (the WIP), and as you suggest, we can have a reset button indeed to reset the view.

**Comment by dmccloskey** [comment]
That sounds good on my end 👍
